### ISSUE TITLE
Enhance offline scout data transfer with QR codes

### ISSUE THREAD

**Issue by Ardaglash** [FIRSTTeam102/scoutradioz#74]
Enable scouts to:

1. Enable a scout to read a QR code of multiple scouting assignments and save the assignments to local storage
2. Enable a scout to read a QR code of a single assignment and set up scouting that robot/match
3. Enable a scout to create a QR code representing the data from one of the match scouting forms in their local storage
4. Also - Be able to create a "one-off" QR code to 'transfer' an assignment to another scout

**Comment by JL102** [comment]
Bullets 1-3 have been taken care of in the most recent version of Voyager. Expanded bullet # 4 into #207. Closing
