### ISSUE TITLE
Enable reporting on aggregate data for events other than the 'current event'

### ISSUE THREAD

**Issue by Ardaglash** [FIRSTTeam102/scoutradioz#85]
When an org is set to a given “current event”, have an easy way to look at aggregated data from a specific previous event and/or “all events”

**Comment by JL102** [comment]
@Ardaglash Potentially fixed as of #203 ?

**Comment by JL102** [comment]
First one (look at data from a specific previous event) completed; second one will be a more significant task and we can write that out in a separate issue. Closing
