### ISSUE TITLE
Add OPR-style “contributed error per scout” to scout vs. FRC audit reporting page

### ISSUE THREAD

**Issue by Ardaglash** [FIRSTTeam102/scoutradioz#91]
Add OPR-style “contributed error per scout” to scout vs. FRC audit reporting page

**Comment by MatPersson** [comment]
I am not familiar enough with the app to know if this is a way to assess inter-rater reliability or just another statistic.  Concern, as scouting Orgs are added, that several scouts may score the same bot, same match.  How is variance in scouting results managed in such cases?  This might be a new enhancement.

**Comment by Ardaglash** [comment]
Good questions! Since each organization can have their own independent data schema, this metric would be designed to be limited to tracking just the scouts in a single org. The intention is to assist the scouting lead in identifying which scouts might need additional training and/or assistance (Team 102 found they had at least one scout in the 2022 season in each category).

**Comment by JL102** [comment]
Feature completed; Closing
