### ISSUE TITLE
Finish interface(s) for manually adding data for off-season events

### ISSUE THREAD

**Issue by Ardaglash** [FIRSTTeam102/scoutradioz#93]
Finish interface(s) for manually adding data for off-season events - pages should send calls into webhook as if TBA were sending data updates

**Comment by JL102** [comment]
Manual data input is complete, but it does not send calls to webhook.
I'm not sure if it should, though, because webhook still sends requests to TBA's API to validate rankings/schedule data.

**Comment by JL102** [comment]
Todo:

1. Infer winner from blue/red scores
2. Foul points
3. Manually adjust rankings because ranking auto calculations aren't perfect

**Comment by JL102** [comment]
1. and 2. fixed by #210

**Comment by Ardaglash** [comment]
3, fixed by #211
